/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class r_rtrk_weatherforecast_MyNDK */

#ifndef _Included_r_rtrk_weatherforecast_MyNDK
#define _Included_r_rtrk_weatherforecast_MyNDK
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     r_rtrk_weatherforecast_MyNDK
 * Method:    convert
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_r_rtrk_weatherforecast_MyNDK_convert
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
